[Ollama]
Scheme = http
Host = 127.0.0.1
Port = 11434
Verify = no
Timeout = 300
ThinkingModel = ministral-3:3b
;Did not work as expected ?
;ThinkingModel = llama3.2:latest

;ThinkingModel = granite4:3b
;ThinkingModel = deepseek-r1:1.5b
;ThinkingModel = qwen3:4b
; ToolModel = qwen3:4b
ToolModel = functiongemma:latest
; ToolModel = granite4:3b
