[Ollama]
Scheme=http
Host=127.0.0.1
Port=11434
Verify=no
Timeout=300
;ThinkingModel=ministral-3:3b
;ThinkingModel=llama3.2:latest Did not work as expected ?
ThinkingModel=deepseek-r1:1.5b
ToolModel=qwen3:4b
